/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_reg.h"

#include "my_adc.h"
#include "my_dsadc.h"
#include "my_tick.h"

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

#define LIGHT_T_ON          2000u
#define LIGHT_T_OFF         2800u

#define CAL_GAIN_MC_PER_LSB LM35_MC_PER_LSB
#define CAL_OFFSET_MC       0


volatile uint16 g_pot =
    0u;

volatile uint16 g_light =
    0u;

volatile sint32 g_mdegc =
    0;


typedef struct
{
    uint16 a;
    uint16 b;

} Median3State;


static uint16 median3_update(
    Median3State *state,
    uint16 x)
{
    uint16 hi =
        (state->a > state->b)
        ? state->a
        : state->b;


    uint16 lo =
        (state->a > state->b)
        ? state->b
        : state->a;


    uint16 middle =
        (x > hi)
        ? hi
        : ((x < lo) ? lo : x);


    state->a =
        state->b;

    state->b =
        x;


    return middle;
}


static void led_init(void)
{
    MODULE_P10.IOCR0.B.PC1 =
        0x10u;

    MODULE_P10.IOCR0.B.PC2 =
        0x10u;

    MODULE_P10.IOCR4.B.PC5 =
        0x10u;

    MODULE_P02.IOCR4.B.PC7 =
        0x10u;

    MODULE_P10.IOCR0.B.PC3 =
        0x10u;
}


static inline void led1(boolean on)
{
    MODULE_P10.OMR.U =
        on
        ? (1u << 1)
        : (1u << (1 + 16));
}


static inline void led2(boolean on)
{
    MODULE_P10.OMR.U =
        on
        ? (1u << 2)
        : (1u << (2 + 16));
}


static inline void rgb(
    boolean red,
    boolean green,
    boolean blue)
{
    MODULE_P10.OMR.U =
          (green
          ? (1u << 5)
          : (1u << (5 + 16)))

        | (blue
          ? (1u << 3)
          : (1u << (3 + 16)));


    MODULE_P02.OMR.U =
        red
        ? (1u << 7)
        : (1u << (7 + 16));
}


static inline void rgb_green(boolean on)
{
    rgb(
        FALSE,
        on,
        FALSE);
}


static void blink_task(uint32 count)
{
    typedef enum
    {
        B_IDLE,
        B_ON,
        B_OFF,
        B_PAUSE

    } BlinkState;


    static BlinkState state =
        B_IDLE;

    static uint32 t0 =
        0u;

    static uint32 left =
        0u;


    switch (state)
    {
        case B_IDLE:

            if (count > 0u)
            {
                left =
                    count;

                t0 =
                    tick_get();

                rgb_green(
                    TRUE);

                state =
                    B_ON;
            }

            break;


        case B_ON:

            if (elapsed(t0, 200u))
            {
                t0 +=
                    200u;

                rgb_green(
                    FALSE);

                state =
                    B_OFF;
            }

            break;


        case B_OFF:

            if (elapsed(t0, 200u))
            {
                t0 +=
                    200u;

                if (--left > 0u)
                {
                    rgb_green(
                        TRUE);

                    state =
                        B_ON;
                }
                else
                {
                    state =
                        B_PAUSE;
                }
            }

            break;


        case B_PAUSE:

            if (elapsed(t0, 1200u))
            {
                state =
                    B_IDLE;
            }

            break;


        default:

            state =
                B_IDLE;

            break;
    }
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    led_init();

    adc_init();

    tick_init();

    dsadc_init();


    static sint32 yLight64 =
        0;

    static sint32 yTemp64 =
        0;


    yLight64 =
        (sint32)
        dsadc_read_once(CH_LDR)
        * 64;


    yTemp64 =
        (sint32)
        adc_read_once(CH_LM35)
        * 64;


    uint32 t0 =
        tick_get();

    uint32 phase =
        0u;

    uint16 filteredPot =
        0u;

    boolean ledOn =
        FALSE;


    static const uint8 order[3] =
    {
        CH_POT,
        CH_LDR,
        CH_LM35
    };


    static Median3State potMedian =
    {
        0u,
        0u
    };

    static Median3State ldrMedian =
    {
        0u,
        0u
    };

    static Median3State tempMedian =
    {
        0u,
        0u
    };


    uint8 index =
        0u;


    dsadc_select(
        order[index]);

        
    while(1)
    {
        if (every_ms(&t0, 10u))
        {
            uint16 value =
                (order[index] == CH_LM35)

                ? adc_read_once(CH_LM35)

                : dsadc_read_current();


            switch (order[index])
            {
                case CH_POT:

                    g_pot =
                        median3_update(
                            &potMedian,
                            value);


                    filteredPot =
                        ma_update(
                            g_pot);

                    break;


                case CH_LDR:
                {
                    uint16 middle =
                        median3_update(
                            &ldrMedian,
                            value);


                    yLight64 +=
                        (sint32)middle
                        - (yLight64 / 64);


                    g_light =
                        (uint16)(
                            yLight64 / 64);


                    if (g_light > LIGHT_T_OFF)
                    {
                        ledOn =
                            FALSE;
                    }
                    else if (g_light < LIGHT_T_ON)
                    {
                        ledOn =
                            TRUE;
                    }


                    led2(
                        ledOn);

                    break;
                }


                case CH_LM35:

                default:

                    yTemp64 +=
                        (sint32)
                        median3_update(
                            &tempMedian,
                            value)

                        - (yTemp64 / 64);


                    g_mdegc =
                          (sint32)(
                              yTemp64 / 64)

                        * (sint32)
                          CAL_GAIN_MC_PER_LSB

                        + (sint32)
                          CAL_OFFSET_MC;

                    break;
            }


            index =
                (uint8)(
                    (index + 1u)
                    % 3u);


            dsadc_select(
                (order[index] == CH_LM35)

                ? CH_POT

                : order[index]);


            phase =
                (phase + 1u)
                & 7u;


            led1(
                (boolean)(
                    phase
                    < ((uint32)filteredPot >> 9)));
        }


        uint32 blinkCount =
            (g_mdegc > 0)

            ? (uint32)g_mdegc
              / 10000u

            : 0u;


        blink_task(
            blinkCount);
    }
}
