/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "my_gpio.h"
#include "my_tick.h"

IfxCpu_syncEvent cpuSyncEvent = 0;


/* RGB 전체 OFF */
static void rgb_all_off(void)
{
    gpio_write(&RGB_R_PORT, RGB_R_PIN, 0);
    gpio_write(&RGB_G_PORT, RGB_G_PIN, 0);
    gpio_write(&RGB_B_PORT, RGB_B_PIN, 0);
}


/* idx에 해당하는 RGB 색 하나 ON */
static void rgb_on(uint8 idx)
{
    if (idx == 0)
    {
        gpio_write(&RGB_R_PORT, RGB_R_PIN, 1);
    }
    else if (idx == 1)
    {
        gpio_write(&RGB_G_PORT, RGB_G_PIN, 1);
    }
    else
    {
        gpio_write(&RGB_B_PORT, RGB_B_PIN, 1);
    }
}


/* LED1 : 100 ms마다 토글 */
static void task_led1(void)
{
    static uint32 t0 = 0;

    if (every_ms(&t0, 100))
    {
        gpio_toggle(&LED1_PORT, LED1_PIN);
    }
}


/* LED2 : 1000 ms마다 토글 */
static void task_led2(void)
{
    static uint32 t0 = 0;

    if (every_ms(&t0, 1000))
    {
        gpio_toggle(&LED2_PORT, LED2_PIN);
    }
}


/* RGB : 250 ms마다 Red → Green → Blue */
static void task_rgb(void)
{
    static uint32 t0 = 0;
    static uint8 idx = 0;

    if (every_ms(&t0, 250))
    {
        rgb_all_off();

        rgb_on(idx);

        idx = (uint8)((idx + 1u) % 3u);
    }
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);


    /* LED 출력 설정 */
    gpio_init_out(&LED1_PORT, LED1_PIN);
    gpio_init_out(&LED2_PORT, LED2_PIN);

    /* RGB 출력 설정 */
    gpio_init_out(&RGB_R_PORT, RGB_R_PIN);
    gpio_init_out(&RGB_G_PORT, RGB_G_PIN);
    gpio_init_out(&RGB_B_PORT, RGB_B_PIN);

    /* RGB 초기 상태 OFF */
    rgb_all_off();


    /* 1 ms STM tick 시작 */
    tick_init();

        
    while(1)
    {
        task_led1();
        task_led2();
        task_rgb();
    }
}
