/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm_reg.h"
#include "IfxSrc_reg.h"
#include "my_gpio.h"

IfxCpu_syncEvent cpuSyncEvent = 0;


/* STM 인터럽트 우선순위 */
#define ISR_PRIO_STM_TICK  10

/* 100 MHz 기준 50,000,000 ticks = 500 ms */
#define PERIOD_TICKS       50000000u


/* 인터럽트가 몇 번 실행됐는지 확인하는 변수 */
volatile uint32 g_isrCount = 0;


/* STM 인터럽트 서비스 루틴 */
IFX_INTERRUPT(isrStmTick, 0, ISR_PRIO_STM_TICK);

void isrStmTick(void)
{
    /* STM CMP0 비교 상태 플래그 지우기 */
    MODULE_STM0.ISCR.U = (1u << 0);

    /* 다음 비교 시점을 500 ms 뒤로 예약 */
    MODULE_STM0.CMP[0].U += PERIOD_TICKS;

    /* LED1 토글 */
    MODULE_P10.OMR.U =
        (1u << LED1_PIN)
        | (1u << (LED1_PIN + 16));

    /* ISR 실행 횟수 증가 */
    g_isrCount++;
}


/* STM 비교 인터럽트 초기화 */
static void stmBlinkInit(void)
{
    /* LED1을 출력으로 설정 */
    gpio_init_out(&LED1_PORT, LED1_PIN);


    /* STM 하위 32비트 전체를 CMP0와 비교 */
    MODULE_STM0.CMCON.U = 0x0000001Fu;

    /* 혹시 남아 있는 CMP0 비교 플래그 정리 */
    MODULE_STM0.ISCR.U = (1u << 0);

    /* 현재 시간으로부터 500 ms 뒤를 첫 비교 시점으로 설정 */
    MODULE_STM0.CMP[0].U =
        MODULE_STM0.TIM0.U + PERIOD_TICKS;


    /* CMP0 비교 사건을 STMIR0으로 보냄 */
    MODULE_STM0.ICR.B.CMP0OS = 0;

    /* CMP0 비교 인터럽트 허용 */
    MODULE_STM0.ICR.B.CMP0EN = 1;


    /* 이전에 남아 있을 수 있는 서비스 요청 정리 */
    SRC_STM0SR0.B.CLRR = 1;

    /* 인터럽트 우선순위 = 10 */
    SRC_STM0SR0.B.SRPN = ISR_PRIO_STM_TICK;

    /* CPU0가 처리 */
    SRC_STM0SR0.B.TOS = 0;

    /* 서비스 요청 허용 */
    SRC_STM0SR0.B.SRE =1;
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    /* STM 비교 인터럽트 초기화 */
    stmBlinkInit();
        
    while(1)
    {


    }
}
