/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "my_gpio.h"
#include "my_tick.h"
#include "my_dht11.h"

IfxCpu_syncEvent cpuSyncEvent = 0;


/*
 * decoder 자체 시험 결과
 *
 * bit 0 : 정상 frame decode
 * bit 1 : checksum 오류 감지
 * bit 2 : 이상 pulse 폭 감지
 * bit 3 : all-zero frame decode
 *
 * 모두 성공하면 0x0F
 */
volatile uint32 g_selfTest = 0;


/* 가짜 DHT11 pulse frame 생성 */
static void make_frame(
    DhtPulse *p,
    const uint8 *bytes)
{
    uint32 i;


    for (i = 0; i < 40u; i++)
    {
        uint8 bit =
            (uint8)(
                (bytes[i / 8u]
                 >> (7u - (i % 8u)))
                 & 1u);


        p[i].lowUs = 50u;

        p[i].highUs =
            bit ? 70u : 27u;
    }
}


/* 실제 센서 없이 decoder 자체 시험 */
static void self_test(void)
{
    static DhtPulse p[40];

    uint8 out[5];


    const uint8 good[5] =
    {55u, 0u, 24u, 0u, 79u};

    const uint8 bad[5] =
    {55u, 0u, 24u, 0u, 80u};

    const uint8 zero[5] =
    {0u, 0u, 0u, 0u, 0u};


    /* 정상 frame */
    make_frame(p, good);

    if (dht_decode_pulses(p, out) == DHT_OK
        && out[0] == 55u
        && out[2] == 24u)
    {
        g_selfTest |=1u;
    }


    /* checksum 오류 검출 */
    make_frame(p, bad);

    if (dht_decode_pulses(p, out)
        == DHT_CHECKSUM)
    {
        g_selfTest |= 2u;
    }


    /* 잘못된 pulse 폭 검출 */
    make_frame(p, good);

    p[7].highUs = 500u;

    if (dht_decode_pulses(p, out)
        == DHT_TIMING)
    {
        g_selfTest |=4u;
    }


    /* all-zero frame 확인 */
    make_frame(p, zero);

    if (dht_decode_pulses(p, out) == DHT_OK
        && out[4] == 0u)
    {
        g_selfTest |= 8u;
    }
}


/* LED1 heartbeat */
static void task_heartbeat(void)
{
    static uint32 t0 = 0;


    if (every_ms(&t0, 100))
    {
        gpio_toggle(
            &LED1_PORT,
            LED1_PIN);
    }
}


/* 정상 DHT11 frame마다 LED2 토글 */
static void task_led2_on_good_frame(void)
{
    static uint32 seenOk = 0;


    if (g_dhtOkCount != seenOk)
    {
        seenOk =
            g_dhtOkCount;


        gpio_toggle(
            &LED2_PORT,
            LED2_PIN);
    }
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    /* LED1 / LED2 출력 */
    gpio_init_out(
        &LED1_PORT,
        LED1_PIN);

    gpio_init_out(
        &LED2_PORT,
        LED2_PIN);
        

    /* 초기 LED OFF */
    gpio_write(
        &LED1_PORT,
        LED1_PIN,
        0);


    /* 1 ms tick 시작 */
    tick_init();


    /*
     * DHT11 decoder 자체 시험
     * 정상이라면 g_selfTest = 0x0F
     */
    self_test();


    /* DHT11 초기화 */
    dht_init();


    while(1)
    {
        task_heartbeat();

        dht_task();

        task_led2_on_good_frame();
    }
}
