/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_reg.h"
#include "my_adc.h"
#include "my_tick.h"

IfxCpu_syncEvent cpuSyncEvent = 0;


#define CAL_GAIN_MC_PER_LSB  LM35_MC_PER_LSB
#define CAL_OFFSET_MC        0


volatile uint16 g_code = 0u;
volatile sint32 g_mdegc = 0;


static void led_init(void)
{
    MODULE_P10.IOCR0.B.PC1 =
        0x10u;
}


static inline void led1(boolean on)
{
    MODULE_P10.OMR.U =
        on
        ? (1u << 1)
        : (1u << (1 + 16));
}


static void blink_task(uint32 count)
{
    typedef enum
    {
        B_IDLE,
        B_ON,
        B_OFF,
        B_PAUSE
    } BlinkState;

    static BlinkState state =
        B_IDLE;

    static uint32 t0 =
        0u;

    static uint32 left =
        0u;


    switch (state)
    {
        case B_IDLE:

            if (count > 0u)
            {
                left = count;

                t0 = tick_get();

                led1(TRUE);

                state = B_ON;
            }

            break;


        case B_ON:

            if (elapsed(t0, 200u))
            {
                t0 += 200u;

                led1(FALSE);

                state = B_OFF;
            }

            break;


        case B_OFF:

            if (elapsed(t0, 200u))
            {
                t0 += 200u;

                if (--left > 0u)
                {
                    led1(TRUE);

                    state = B_ON;
                }
                else
                {
                    state = B_PAUSE;
                }
            }

            break;


        case B_PAUSE:

            if (elapsed(t0, 1200u))
            {
                state = B_IDLE;
            }

            break;


        default:

            state = B_IDLE;

            break;
    }
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    led_init();

    adc_init();

    tick_init();


    static sint32 y64 = 0;


    /*
     * 첫 LM35 sample로
     * IIR 상태값 초기화
     */
    y64 =
        (sint32)adc_read_once(CH_LM35)
        * 64;


    uint32 t0 =
        tick_get();

        
    while(1)
    {
        /*
         * 10 ms마다 LM35 측정
         */
        if (every_ms(&t0, 10u))
        {
            sint32 x =
                (sint32)adc_read_once(CH_LM35);


            /*
             * IIR low-pass filter
             * alpha = 1/64
             */
            y64 +=
                x - (y64 / 64);


            /*
             * 필터된 ADC code
             */
            g_code =
                (uint16)(y64 / 64);


            /*
             * ADC code
             * → milli-degree Celsius
             */
            g_mdegc =
                  (sint32)g_code
                * (sint32)CAL_GAIN_MC_PER_LSB
                + (sint32)CAL_OFFSET_MC;
        }


        /*
         * 온도의 십의 자리만큼 blink
         *
         * 23℃ → 2번
         * 35℃ → 3번
         */
        uint32 blinkCount =
            (g_mdegc > 0)
            ? (uint32)g_mdegc / 10000u
            : 0u;


        blink_task(
            blinkCount);
    }
}
