/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_reg.h"
#include "my_adc.h"
#include "my_tick.h"

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

#define LIGHT_T_ON   1200u
#define LIGHT_T_OFF  1400u

static void led_init(void)
{
    MODULE_P10.IOCR0.B.PC2 =
        0x10u;
}


static inline void led2(boolean on)
{
    MODULE_P10.OMR.U =
        on
        ? (1u << 2)
        : (1u << (2 + 16));
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    led_init();

    adc_init();

    tick_init();

    static sint32 y64 = 0;

    uint32 t0 =
        tick_get();

    boolean ledOn =
        FALSE;

    uint16 filtered =
        0u;

        
    while(1)
    {
        if (every_ms(&t0, 10u))
        {
            uint16 middle =
                med3_update(
                    adc_read_once(CH_LDR));


            /*
             * IIR low-pass filter
             * alpha = 1/64
             */
            y64 +=
                (sint32)middle
                - (y64 / 64);


            filtered =
                (uint16)(
                    y64 / 64);


            /*
             * hysteresis
             */
            if (filtered > LIGHT_T_OFF)
            {
                ledOn = FALSE;
            }
            else if (filtered < LIGHT_T_ON)
            {
                ledOn = TRUE;
            }


            /*
             * 1200~1400 사이에서는
             * ledOn 값을 그대로 유지
             */
            led2(ledOn);
        }
    }
}
