/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxScu_reg.h"
#include "IfxStm_reg.h"
#include "IfxSrc_reg.h"
#include "my_gpio.h"

IfxCpu_syncEvent cpuSyncEvent = 0;

/* SW1 인터럽트 우선순위 */
#define ISR_PRIO_SW1   20

/* 100 MHz 기준 2,000,000 ticks = 20 ms */
#define DEBOUNCE_TICKS 2000000u


/* main에게 버튼 사건이 있었다고 알리는 플래그 */
volatile boolean g_sw1Event = FALSE;

/* 정상적으로 받아들인 버튼 누름 횟수 */
volatile uint32 g_pressCnt = 0;

/* 정상적으로 받아들인 버튼 누름 횟수 */
static uint32 s_lastEdge = 0;


/* SW1용 ERU 초기화 */
static void eruInitSw1(void)
{
    /* SW1 = pull-up 입력 */
    gpio_init_in_pullup(&SW1_PORT, SW1_PIN);

    /* LED2 = 출력 */
    gpio_init_out(&LED2_PORT, LED2_PIN);


    /*
     * ERU input channel 3에
     * P02.0(SW1)을 연결
     */
    MODULE_SCU.EICR[1].B.EXIS1 = 2;

    /* High → Low, 즉 버튼 누름 에지를 검출 */
    MODULE_SCU.EICR[1].B.FEN1 = 1;

    /* Low → High, 즉 버튼 놓는 에지는 무시 */
    MODULE_SCU.EICR[1].B.REN1 = 0;

    /* INTF3를 software-clear sticky flag로 사용 */
    MODULE_SCU.EICR[1].B.LDEN1 = 0;


    /* 설정 중에는 trigger를 막아 둠 */
    MODULE_SCU.EICR[1].B.EIEN1 = 0;

    /* ERU trigger를 OGU0으로 보냄 */
    MODULE_SCU.EICR[1].B.INP1 = 0;

    /* trigger가 발생하면 IOUT0 활성화 */
    MODULE_SCU.IGCR[0].B.IGP0 = 1;


    /* 오래된 ERU 입력 flag 정리 */
    MODULE_SCU.FMR.U = (1u << 19);

    /* 오래된 서비스 요청 정리 */
    SRC_SCUERU0.B.CLRR = 1;


    /* ERU trigger 허용 */
    MODULE_SCU.EICR[1].B.EIEN1 = 1;

    /* 인터럽트 priority = 20 */
    SRC_SCUERU0.B.SRPN = ISR_PRIO_SW1;

    /* CPU0가 처리 */
    SRC_SCUERU0.B.TOS = 0;

    /* 서비스 요청 허용 */
    SRC_SCUERU0.B.SRE = 1;
}


/* SW1 인터럽트 등록 */
IFX_INTERRUPT(isrSw1, 0, ISR_PRIO_SW1);


/* SW1 ISR */
void isrSw1(void)
{
    uint32 now = MODULE_STM0.TIM0.U;


    /*
     * 마지막으로 인정한 버튼 에지로부터
     * 20 ms 이상 지났는지 확인
     */
    if ((uint32)(now - s_lastEdge) >= DEBOUNCE_TICKS)
    {
        s_lastEdge = now;


        /* LED2 토글 */
        MODULE_P10.OMR.U =
            (1u << LED2_PIN)
            | (1u << (LED2_PIN + 16));


        /* main에게 사건 발생 알림 */
        g_sw1Event = TRUE;


        /* 정상 버튼 누름 횟수 증가 */
        g_pressCnt++;
    }

    /*
     * 20 ms 안에 들어오는 추가 에지는
     * 버튼 바운스로 보고 무시
     */
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);


    /* ERU 버튼 인터럽트 초기화 */
    eruInitSw1();

    while(1)
    {
        boolean event = FALSE;


        if (g_sw1Event)
        {
            boolean interruptState;

            /*
             * g_sw1Event를 읽고 FALSE로 지우는 동안
             * 새로운 ISR이 끼어들지 못하게 잠깐 막음
             */
            interruptState = IfxCpu_disableInterrupts();


            event = g_sw1Event;
            g_sw1Event = FALSE;

            IfxCpu_restoreInterrupts(interruptState);
        }

        if (event)
        {
            /*
             * 버튼 누른 뒤 시간이 오래 걸리는 작업이 필요하면
             * ISR이 아니라 여기에 작성
             */
        }
    }
}
