/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "my_adc.h"
#include "my_tick.h"
#include "my_scan.h"

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

#define SCAN_PERIOD_MS  10u
#define VREF_MV         5000u
#define MAX_AGE_MS      50u


volatile uint32 g_ageMs =
    0u;

volatile uint16 g_positionPermille =
    0u;

volatile uint32 g_potMv =
    0u;

volatile uint32 g_staleCount =
    0u;


/*
 * 가변저항 ADC 값을
 * 위치 비율과 전압으로 환산
 */
static void pot_meanings(uint16 raw)
{
    uint32 code =
        (uint32)raw;


    /*
     * 0      → 0
     * 4095   → 1000
     *
     * permille 단위
     */
    g_positionPermille =
        (uint16)(
            (code * 1000u + 2047u)
            / 4095u);


    /*
     * 5 V reference 가정
     */
    g_potMv =
        (code * VREF_MV)
        / 4096u;
}


static void task_scan(void)
{
    static uint32 t0 =
        0u;

    ScanStatus status;


    /*
     * 10 ms마다 새 scan 요청
     */
    if (every_ms(
            &t0,
            SCAN_PERIOD_MS))
    {
        (void)scan_start();
    }


    /*
     * 현재 scan의 결과 수집
     */
    status =
        scan_service();


    /*
     * 세 채널 전부 성공했을 때
     */
    if (status == SCAN_OK)
    {
        pot_meanings(
            g_published.pot);
    }


    /*
     * 마지막 정상 record가
     * 얼마나 오래됐는지
     */
    g_ageMs =
        scan_age_ms(
            tick_get());


    /*
     * 50 ms보다 오래되면
     * stale 관찰 횟수 증가
     */
    if (g_ageMs > MAX_AGE_MS)
    {
        g_staleCount++;
    }
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    tick_init();

    adc_init();

        
    while(1)
    {
        task_scan();
    }
}
