/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_reg.h"

#define DEBOUNCE_SAMPLES 20u

IfxCpu_syncEvent cpuSyncEvent = 0;

static void delay_ms_approx(unsigned int ms)
{
    volatile unsigned int i;

    while (ms--)
    {
        for (i = 0; i < 20000u; i++)
        {
        }
    }
}

void core0_main(void)
{
    unsigned int raw;
    unsigned int stable = 0u;
    unsigned int prev_stable = 0u;
    unsigned int count = 0u;

    IfxCpu_enableInterrupts();

    IfxScuWdt_disableCpuWatchdog(
        IfxScuWdt_getCpuWatchdogPassword()
    );

    IfxScuWdt_disableSafetyWatchdog(
        IfxScuWdt_getSafetyWatchdogPassword()
    );

    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    /* P10.2 = LED2, push-pull 출력 */
    P10_IOCR0.B.PC2 = 0x10;

    /* P02.1 = SW2, pull-up 입력 */
    P02_IOCR0.B.PC1 = 0x02;

    while (1)
    {
        /* SW2는 누르면 Low이므로,
         * 이후 로직에서는 눌림을 1로 바꿔 사용 */
        raw = ((P02_IN.U & (1u << 1)) == 0u) ? 1u : 0u;

        if (raw != stable)
        {
            count++;

            if (count >= DEBOUNCE_SAMPLES)
            {
                stable = raw;
                count = 0u;
            }
        }
        else
        {
            count = 0u;
        }

        /* 안정된 상태가 0 → 1로 변한 순간만 새 눌림 */
        if ((stable == 1u) && (prev_stable == 0u))
        {
            P10_OMR.U = (1u << 2) | (1u << 18);
        }

        prev_stable = stable;

        delay_ms_approx(1);
    }
}
