/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_reg.h"
#include "my_adc.h"
#include "my_tick.h"

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;


#define RB_N 32u

static volatile uint16 s_rb[RB_N];

static volatile uint32 s_head = 0u;
static volatile uint32 s_tail = 0u;


/* ADC ISR이 새 값을 넣음 */
static inline void rb_put(uint16 value)
{
    uint32 head = s_head;

    s_rb[head & (RB_N - 1u)] =
        value;

    s_head =
       head + 1u;
}


/* main이 값을 하나 꺼냄 */
static inline boolean rb_get(uint16 *value)
{
    if (s_tail == s_head)
    {
        return FALSE;
    }

    *value =
        s_rb[s_tail & (RB_N - 1u)];
    s_tail++;

    return TRUE;
}

/* ADC 결과 interrupt */
IFX_INTERRUPT(isrAdcG4, 0, ISR_PRIO_ADC);

void isrAdcG4(void)
{
    /*
     * RES7을 한 번 읽음.
     * 읽으면 VF도 clear.
     */
    uint32 result =
        MODULE_VADC.G[4].RES[7].U;

    rb_put(
        (uint16)(
            result & 0x0FFFu));
}

static void led_init(void)
{
    MODULE_P10.IOCR0.B.PC1 =
        0x10u;
}

static inline void led1(boolean on)
{
    MODULE_P10.OMR.U =
        on
        ? (1u << 1)
        : (1u << (1+16));
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    led_init();

    adc_init();

    adc_start_tick_stream();

    tick_init();


    uint16 raw = 0u;
    uint16 filtered = 0u;

    uint32 t0 =
        tick_get();

    uint32 phase = 0u;
        

    while(1)
    {
        /*
         * 도착한 ADC sample 모두 처리
         */
        while (rb_get(&raw))
        {
            filtered =
                ma_update(raw);
        }


        /*
         * 10 ms마다 PWM phase 한 칸 진행
         */
        if (every_ms(&t0, 10u))
        {
            phase =
                (phase + 1u) & 7u;

            /*
             * ADC 0~4095
             * → brightness 단계 0~7
             */
            uint32 duty8 =
                (uint32)filtered >> 9;

            led1(
                (boolean)(
                    phase < duty8));
        }
    }
}
